DEFAULT_ALLOWED_HOSTS = "localhost,127.0.0.1"
DEFAULT_CSRF_TRUSTED_ORIGINS = "http://localhost,http://127.0.0.1"
DEFAULT_PAGE_SIZE = 6
DEFAULT_SQLITE_DB_NAME = "db.sqlite3"

TAG_NAME_MAX_LENGTH = 200
TAG_SLUG_MAX_LENGTH = 200
TAG_COLOR_MAX_LENGTH = 7
TAG_COLOR_DEFAULT = "#FFFFFF"

INGREDIENT_NAME_MAX_LENGTH = 128
INGREDIENT_UNIT_MAX_LENGTH = 64

RECIPE_NAME_MAX_LENGTH = 256
SHORT_LINK_CODE_MAX_LENGTH = 16

COOKING_TIME_MIN = 1
COOKING_TIME_MAX = 1440

INGREDIENT_AMOUNT_MIN = 1
INGREDIENT_AMOUNT_MAX = 2_147_483_647

HEX_COLOR_PATTERN = r"^#[0-9A-Fa-f]{6}$"
