# Generated by Django 4.2.24 on 2025-09-20 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_update_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={
                "default_related_name": "shopping_carts",
                "verbose_name": "Элемент списка покупок",
                "verbose_name_plural": "Список покупок",
            },
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
